services:
  postgres_db:
    image: postgres:17
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=docker_user
      - POSTGRES_PASSWORD=docker_pass
    volumes:
      - my_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker_user -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 3
      # start_period: 30s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:8000
    environment:
      - TESTING=${TESTING:-False}
      - DEBUG=${DEBUG:-False}
      - DATABASE_URL=postgres://docker_user:docker_pass@postgres_db:5432/test_db
      - SECRET_KEY=${SECRET_KEY}
    command: sh -c "python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  my_data:
