name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  postgres-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: ci_user
          POSTGRES_PASSWORD: ci_password
        options: >-
          --health-cmd "pg_isready -U ci_user -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      DATABASE_URL: postgres://ci_user:ci_password@localhost:5432/test_db
      TESTING: "false"
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set-up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U ci_user && break
            echo "Waiting for Postgres..."
            sleep 2
          done
          python manage.py migrate --noinput

      - name: Run linters
        run: |
          pip install flake8
          flake8 --max-line-length=88 --exclude=*/migrations/*

      - name: Run Tests
        run: python manage.py test tests

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: postgres-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set IMAGE_NAME
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/${OWNER}/blogpost-api
          echo "SHA_NAME=$IMAGE_NAME:ci-${{ github.sha }}" >> $GITHUB_ENV
          TAG=${GITHUB_REF#refs/tags/}
          echo "VERSION=${IMAGE_NAME}:$TAG" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t $SHA_NAME -t $VERSION .

      - name: Push Images
        run: |
          docker push $SHA_NAME
          docker push $VERSION
