name: Rashisky Blogpost

on:
  push:
    branches: ["main"]
    tags: ["v*"]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 10s
          --health-retries 3
          --health-timeout 5s

    env:
      DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
      TESTING: false
      DEBUG: false
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set-up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply migrations
        run: |
          for i in {1..20}; do
              pg_isready -U test_user -d test_db && break
              echo "Waiting for Postgress DB..."
              sleep 2
          done
          python3 manage.py migrate --noinput

      - name: Run linters
        run: |
          flake8

      - name: Run Tests
        run: |
          python manage.py test api/v1/
          pytest api/v2/

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set IMAGE_NAME and SHA_NAME
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_PREFIX=ghcr.io/${OWNER}/blogpost-api
          echo "SHA_NAME=${IMAGE_PREFIX}:ci-${{ github.sha }}" >> ${GITHUB_ENV}
          TAG=${GITHUB_REF#refs/tags/}
          echo "IMAGE_NAME=${IMAGE_PREFIX}:${TAG}" >> ${GITHUB_ENV}
          echo "API_VERSION=${TAG%%.*}" >> ${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: github.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${SHA_NAME} -t ${IMAGE_NAME} --build-arg API_VERSION=${API_VERSION} .

      - name: Push Images
        run: |
          docker push $SHA_NAME
          docker push $IMAGE_NAME
